#!/bin/sh

set -e
umask 0002

if [ "$1" == "--" ]; then

  /usr/bin/sudo /usr/bin/systemctl --quiet enable named.service

  if test ! -f "disabled.bin"; then
    echo "dns resolver is already enabled."
  else
    rm "disabled.bin"
    if systemctl is-active --quiet bind-autodiscovery.service; then
      /usr/bin/sudo /usr/bin/systemctl restart bind-autodiscovery.service
      /usr/bin/sudo /usr/bin/systemctl restart named.service
      /usr/bin/sudo /usr/bin/systemctl restart bind-postdiscovery.service
    else
      echo "dns resolver will be enabled on next reboot."
    fi
  fi

fi

